name: Java_Homework2

on:
  push:
    branches:
      - main, java_homework2
  pull_request:
    branches:
      - main, java_homework2

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: JDK
        uses: actions/setup-java@v1
        with:
          java-version: '17'
      - name: Maven
        run: mvn clean install
